version: "3.9"

services:
  app:
    build: .
    container_name: oracle-challenge-app
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network
    user: "1000:1000"
    environment:
      - TZ=America/Sao_Paulo
    working_dir: /app
    command: ["java", "-jar", "app.jar"]

networks:
  app-network:
    driver: bridge
